### ISSUE TITLE
Crashes when trying to load the wrong type from the settings file

### ISSUE THREAD

**Issue by fourtf** [pajlada/settings#8]
Tested with changing a float to an int and a boolean to a string.

Steps to reproduce:

1. open a settings.json file
2. change a value to a different type, e.g. `1` ⇒ `1.2` or `true` ⇒ `"asd"`

**Comment by pajlada** [comment]
Fixed in latest version

1.2 would be read as 1
1.7 would be read as 2
trying to read a bool from a json string value would just return in the bool's default value

Exceptions are still possible to enable with the `PAJLADA_SETTINGS_ENABLE_EXCEPTIONS` macro
